name: couriers_workspace
description: A workspace for the couriers project.

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - courier_app
  - dispatcher_app
  - packages/shared_data
  - packages/shared_ui
dependencies:
  yandex_maps_mapkit: ^4.26.0-beta
  flutter_dotenv: ^6.0.0
