name: shared_ui
description: A new Flutter package project.

publish_to: 'none'
resolution: workspace

version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
